#!/usr/bin/bash
##################################################
#
# (c) 2020 Adams Vallejos <adams.vallejos@gu.se>
#
##################################################
# USAGE: log in to backup and execute
#        bash fileLister

# Choose the name of your list
FILENAME=$(zenity --entry --title "List name" --text "Please choose a filename (.lst):")
if [ -e $FILENAME.lst ]
then
    zenity --warning --text="Aborting, file exists."
    exit
else
    touch $FILENAME.lst
fi

# # Data path
# zenity --entry --title "Data directory" --text "Enter the path of your data:" --ok-label="Accept"

# exit
# STAGE 1
# Choose files from GUI
if true
    then
        zenity --file-selection --multiple --filename "${HOME}/${USER}" --separator=$'\n' >> $FILENAME.lst
    else
        exit
exit

# Add more files
zenity --question --text "Do you want to add more files?" --no-wrap --ok-label "Yes" --cancel-label "No" --title "Add more files"
# RETURN TO STAGE !

