#!/bin/sh
#
#    Author: Adams Vallejos
#       USAGE put in /etc/update-motd.d/ with sudo chmod +x permission
#	NOTE: differences in decimal notation of the uptime command  when executed at startup vs
#		executed from terminal (dot vs comma)
#
USERS=$(who | cut -f 1 -d ' ' | sort -u|wc -l)
CPUS=$(printf "%.0f\n" `cat /proc/loadavg | cut -f 3 -d' '`)
echo "\e[1;32mHi $(logname), welcome to $(hostname)!\e[0m"
if [ "$CPUS" -lt 64 ] 
then
        echo "\e[1;32m > $((64 - $CPUS)) CPUs are available\e[0m"
        echo "\e[1;33m > Limit your jobs to 20 CPUs\e[0m"
else
	echo "\e[1;31m > This server is busy, there are $(($CPUS - 64)) jobs queued.\e[0m"
fi
