#!/bin/sh
#
#    Author: Adams Vallejos
#

USERS=$(uptime | cut -f 7 -d' ')
CPUS=$(uptime | cut -f 14 -d' ')

echo "\e[1;33mHi $(whoami), welcome to $(hostname)!\e[0m"
echo "  There are currently $USERS users logged in"
echo "  $CPUS CPUs are now busy."
echo "  \033[5mLimit your Jobs to 20 CPUs\033[0m"
echo $PERCENTAGE